site_name: PetrSU Docs
repo_url: https://github.com/WilliamAdamsWAG/petrsu_labs
theme:
  name: material
  language: ru
  icon:
    repo: fontawesome/brands/github
  features:
    - search.suggest
    - search.highlight
    - navigation.top
    - navigation.path
    - navigation.instant
    - navigation.instant.progress
    - content.code.copy
    - content.code.select
    - content.code.annotate
  custom_dir: overrides

nav:
  - 'Главная': 'index.md'
  - 'Linux':
    - 'Команды терминала': 'linux/bash.md'
  - 'Лабораторные':
    - 'Лабораторная 1': 'labs/lab1.md'
    - 'Лабораторная 2': 'labs/lab2.md'

plugins:
  - search
  - tags

markdown_extensions:
- pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.critic
- pymdownx.caret
- pymdownx.keys
- pymdownx.mark
- pymdownx.tilde
- attr_list
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- admonition
- pymdownx.details
