site_name: PetrSU Docs
site_url: https://edu.william-adams.ru
repo_url: https://github.com/WilliamAdamsWAG/petrsu_labs

copyright: Copyright &copy; 2025 William Adams

extra:
    social:
        - icon: fontawesome/brands/telegram
          link: https://t.me/WilliamAdams_group
          name: По любым вопросам

nav:
    - 'Главная': 'index.md'
    - 'Лабораторные':
        - '№1 Hello, Students!': 'labs/lab1.md'
        - '№2 Нужный этаж': 'labs/lab2.md'
    - 'Linux':
        - 'Команды терминала': 'linux/bash.md'
    - 'Инструменты':
        - 'make': 'tools/make.md'
        - 'PuTTy': 'tools/putty.md'
        - 'Termius': 'tools/termius.md'

theme:
    name: material
    language: ru

    icon:
        repo: fontawesome/brands/github

    features:
        - search.suggest
        - search.highlight
        - navigation.top
        - navigation.path
        - navigation.footer
        - navigation.instant
        - navigation.instant.progress
        - content.code.copy
        - content.code.select
        - content.code.annotate

    custom_dir: overrides

markdown_extensions:
- attr_list
- admonition
- md_in_html

- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.critic
- pymdownx.caret
- pymdownx.keys
- pymdownx.mark
- pymdownx.tilde
- pymdownx.details

- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg

- pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

plugins:
    - search
    - tags
